---
# #####
# TERRAFORM LIFECYCLE MANAGED
# All changes will be overwritten
#####
# https://docs.github.com/en/actions/reference
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners
name : default
on :
  push :
    branches : [ "main" ]
    tags : [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request :
    types :
    - "opened"
    - "reopened"
    - "synchronize"

jobs :
  default :
    runs-on : ubuntu-latest
    steps :
    - name : checkout
      uses : "actions/checkout@v2"
    - name : docker build current
      run : "docker build --tag $GITHUB_REPOSITORY:$GITHUB_SHA --file ./Dockerfile ."
    - name : docker build latest
      run : "docker build --tag $GITHUB_REPOSITORY:latest --file ./Dockerfile ."
    - name : docker images all
      run : "docker images --all"
    - name : npm install
      run : "npm install"
    - name : npx release
      env : { GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}" }
      run : "npx semantic-release"

